version: '3'
services:
    api:
        container_name: wallet-api
        build:
            dockerfile: Dockerfile
            context: .
            # Only will build development stage from our dockerfile
            target: production
        volumes:
            - .:/usr/src/app
        env_file:
            - .env
        ports:
            - 3001:3001
        networks:
            - wallet-network
    postgres:
        image: postgres:14.1-alpine
        container_name: wallet-db
        restart: always
        volumes:
            - "postgres-data:/var/lib/postgresql/data"
        environment:
            - POSTGRES_USER=wallet
            - POSTGRES_PASSWORD=c4f7a7be-69f6-4daa-bcba-72f3838269cc
            - POSTGRES_DB=wallet
        ports:
            - "5444:5432"
        networks:
            - wallet-network
networks:
  wallet-network:
    driver: bridge
volumes:
    cache:
        driver: local
    postgres-data:
